In [1]:
# Quando estamos interessados em representar coleções de vetores, as matrizes são uma maneira 
# inteligente e simplificada que nos auxiliam nessa atividade.
# Os elmentos das matrizes podem ser números reais, números complexos, expressões algébricas e até funções. 
# Matrizes são compostas por linhas e colunas.
# Assim como acontece com os vetores, as matrizes precisam possuir elemntos  de mesmo tipo.

In [2]:
import numpy as np

In [3]:
# Define uma matriz com 2 linhas e 3 colunas
a = np.array([[1,2,3,],[3,4,5]])

In [4]:
type(a)

numpy.ndarray

In [5]:
# Define uma matriz de 3 linhas e 3 colunas
a2 = np.matrix([[1,2,3],[3,4,5]])

In [6]:
type(a2)

numpy.matrix

In [7]:
# Acessando elementos da linha 2 e coluna 3
a[1,2]

5

In [8]:
# Obter todos os elementos da linha 1
a[0,:]

array([1, 2, 3])

In [9]:
# Obter todos os elementos da coluna 2
a2[:,1]

matrix([[2],
        [4]])

In [10]:
# mantendo o mesmo tipo de elementos em um vetor também acontece com as matrizes.

In [11]:
import numpy as np

In [12]:
b = np.array([[1,2,3],[3,4,'5']])

In [13]:
b

array([['1', '2', '3'],
       ['3', '4', '5']], dtype='|S21')

In [14]:
type(b[0][0])

numpy.string_

In [15]:
# como nos vetores os elementos da coluna e da linha foram transformados em str.

In [16]:
# -> Operações básicas com vetores e matrizes

In [17]:
import numpy as np

In [18]:
# Definir o vetor
v =np.array([[11,22,33]])

In [19]:
# Define uma matriz
a = np.array([[1,2,3],[4,5,6]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Define uma matriz
b = np.array([[1,1,1],[2,3,3]])

In [22]:
# Soma o vetor com a matriz
sva = v + a

In [23]:
sva

array([[12, 24, 36],
       [15, 27, 39]])

In [25]:
#  Multiplica o vetor 'v' pela matriz 'a'
va = v*a

In [26]:
va

array([[ 11,  44,  99],
       [ 44, 110, 198]])

In [27]:
# Soma dos elementos das matrizes
c = a + b

In [28]:
c

array([[2, 3, 4],
       [6, 8, 9]])

In [30]:
# Operações com mattrizes
d = 2*a+b

In [31]:
d

array([[ 3,  5,  7],
       [10, 13, 15]])

In [32]:
# Devemos ter cuidado nas operações de multiplicação, porque temos dois tipos de produtos 
# entre matrizes: produto entr os escalares da matriz e o produto matricial

In [33]:
# Multiplica elementos das matrizes
mab = a * b

In [34]:
mab

array([[ 1,  2,  3],
       [ 8, 15, 18]])

In [36]:
# Multiplicação matricial
dab = np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [38]:
# Na multiplicação matricial precissamos de uma concordância dimensional entre o número
# de colunas de uma matriz com o número de linhas da outra
# Para multiplicação matricial devemos ter
# nº de colunas de 'a' igual nº de linhas de 'b'
dab = np.dot(a,b.T) # b.T -> transporta de 'b'

In [39]:
dab

array([[ 6, 17],
       [15, 41]])

In [ ]:
# Como a mmatriz 'a' apresenta três colunas e a matriz 'b' possui apenas duas linhas,
# foi preciso obter a transposta de 'b' trnasformado as linhas em colunas ecolunas em linhas.
# Dessa forma foi possível obter a consistência necessária para o produto matricial.